version: '3'

services:
  backend:
    build:
      context: ./app
    restart: always
    volumes:
      - static_volume:/usr/src/app/static_files
    env_file:
      - ./app/config/.env
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - ./database/data:/var/lib/postgresql/data/
      - ./database/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
    environment:
      - POSTGRES_DB=movies_database
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=123qwe
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/static_files/
      - ./nginx/conf.d/site.conf:/etc/nginx/conf.d/site.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
  